export const SET_PARAMS = 'SET_PARAMS';
export const FETCH_BANK_REQUEST = 'FETCH_BANK_REQUEST';
export const FETCH_BANK_SUCCESS = 'FETCH_BANK_SUCCESS';
export const FETCH_BANK_FAILURE = 'FETCH_BANK_FAILURE';
export const SET_DROPDOWN_OPTION = 'SET_DROPDOWN_OPTION';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const SET_FAVORITE = 'SET_FAVORITE';
